#Load the data
dt<-read.table("household_power_consumption.txt",header=TRUE,sep=";")
#Subset
dt$Date <- as.Date(dt$Date, format='%d/%m/%Y')
sub_dt <- subset(dt, (dt$Date == '2007-02-01')|(dt$Date == '2007-02-02'))
#Transfrom the data format
time <- paste(sub_dt$Date, sub_dt$Time)
time <- strptime(time, format="%Y-%m-%d %H:%M:%S")
names <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
Global_active_power <- as.numeric(as.character(sub_dt$Global_active_power))
Voltage <- as.numeric(as.character(sub_dt$Voltage))
Sub_metering_1 <- as.numeric(as.character(sub_dt$Sub_metering_1))
Sub_metering_2 <- as.numeric(as.character(sub_dt$Sub_metering_2))
Sub_metering_3 <- as.numeric(as.character(sub_dt$Sub_metering_3))
Global_reactive_power <- as.numeric(as.character(sub_dt$Global_reactive_power))
#Draw the plot
par(mfrow=c(2,2))
Sys.setlocale(category = "LC_ALL", locale = "C")
plot(time,Global_active_power,type='l',xlab="",ylab="Global Active Power (kilowatts)")
plot(time,Voltage,type='l',xlab="datetime",ylab="Voltage")
plot(time,Sub_metering_1,type="l",ylab="Energy sub metering",xlab="")
lines(time,Sub_metering_2, col = "red")
lines(time,Sub_metering_3, col = "blue")
legend("topright",legend = names, lty =1, col = c("black", "red", "blue"),bty="n")
plot(time,Global_reactive_power,type='l',xlab="datetime",ylab="Global_reactive_power")
